name: Deploy to Google Play Store

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.7

      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON | base64 -di > app/google-services.json

      - name: Create keystore.properties
        run: |
          touch keystore.properties
          echo "apiKey=${{ secrets.API_KEY }}" >> keystore.properties

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew clean testDebug

# first test now build abb file and distribute it to google play store

  distribute:
    name: Deploy to Google Play Store
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.7

      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON | base64 -di > app/google-services.json

      - name: Create keystore.properties
        run: |
          touch keystore.properties
          echo "apiKey= ${{ secrets.API_KEY }}" >> keystore.properties 

      - name: Grant execute permissions for gradlew  # Added this step
        run: chmod +x gradlew
          
      - name: Assemble release bundle
        run: ./gradlew bundleRelease

      - name: Sign the release bundle
        uses: r0adkll/sign-android-release@v1
        with:
            releaseDirectory: app/build/outputs/bundle/release
            signingKeyBase64: ${{ secrets.RECIPE_KEYSTORE }}
            keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
            alias: ${{ secrets.RECIPE_ALIAS }}
            keyPassword: ${{ secrets.RECIPE_ALIAS_PASSWORD }}

      - name: Setup Authorization with Google Play Store
        env:
          PLAY_CONFIG_JSON: ${{ secrets.PLAY_CONFIG }}
        run: echo $PLAY_CONFIG_JSON | base64 -di > play_config.json

      - name: Setup Ruby Environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.6
          bundler-cache: true

      - name: Install bundler
        run: | 
         gem install bundler
         bundle install

      - name: Upload the release bundle to Google Play Store
        run: bundle exec fastlane upload_to_play_store
